name: Dandelion-dev CI

on:
  workflow_dispatch:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_windows_x64_msvc:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Create build dir
        run: |
          New-Item -ItemType "directory" build
        shell: powershell
      
      - name: Generate VS build file with CMake
        run: cmake -G "Visual Studio 16 2019" -S . -B build
        shell: powershell
      
      - name: Build Dandelion
        run: cmake --build build --config Release --target dandelion --parallel $Env:NUMBER_OF_PROCESSORS
        shell: powershell
      
      - name: Copy resources
        run: Copy-Item -Path ".\build\resources" -Destination ".\build\Release\resources" -Recurse
        shell: powershell
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dandelion-windows-x64-msvc
          path: ./build/Release

  build_lib_windows_x64_msvc:
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@v2
      
      - name: Create build dir
        run: |
          New-Item -ItemType "directory" "lib\build"
        shell: powershell
      
      - name: Generate VS build file with CMake
        run: cmake -G "Visual Studio 16 2019" -S ".\lib" -B ".\lib\build"
        shell: powershell
      
      - name: Build Dandelion-lib
        run: |
          cmake --build ".\lib\build" --config Debug --target dandelion-bvh --parallel $Env:NUMBER_OF_PROCESSORS
          cmake --build ".\lib\build" --config Debug --target dandelion-ray --parallel $Env:NUMBER_OF_PROCESSORS
          cmake --build ".\lib\build" --config Release --target dandelion-bvh --parallel $Env:NUMBER_OF_PROCESSORS
          cmake --build ".\lib\build" --config Release --target dandelion-ray --parallel $Env:NUMBER_OF_PROCESSORS
        shell: powershell
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dandelion-lib-windows-x64-msvc
          path: |
            ./lib/build/Debug
            ./lib/build/Release

  build_windows_x64_mingw:
    runs-on: windows-2019
    strategy:
      matrix:
        include:
          - { sys: mingw64 }
          - { sys: ucrt64 }
          - { sys: clang64 }
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{matrix.sys}}
          update: true
          install: >-
            git
            make
          pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
      
      - name: Create build dir
        run: mkdir build
      
      - name: Generate build file
        run: cmake -G Ninja -S . -B build -DCMAKE_BUILD_TYPE=Release
      
      - name: Build Dandelion
        run: cmake --build build # ninja always runs in parallel
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dandelion-windows-x64-mingw-${{matrix.sys}}
          path: |
            build/dandelion.exe
            build/resources

  build_linux:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout dandelion-autobuild
        uses: actions/checkout@v4
        with:
          repository: XJTU-Graphics/dandelion-autobuild

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: dandelion-dev

      - name: Update rolling distribution images
        run: |
          python3 build_all.py -u
        shell: bash

      - name: Build docker images
        run: |
          python3 build_all.py -im
        shell: bash      

      - name: Build dandelion
        run: |
          python3 build_all.py -b
        shell: bash

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dandelion-linux-x64
          path: logs

  build_macos:
    runs-on: macos-13
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Create build dir
        run: mkdir build
      
      - name: Generate build file
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
      
      - name: Build Dandelion
        run: cmake --build build --target dandelion --parallel $(sysctl -n hw.activecpu)
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dandelion-macos-x64
          path: |
            build/dandelion
            build/resources
